# Generated by Django 2.2.7 on 2019-12-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('combustivel', models.CharField(max_length=200, verbose_name='combustível')),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('chassi', models.CharField(max_length=17, unique=True)),
                ('ano', models.IntegerField()),
                ('capacidade', models.IntegerField()),
            ],
            options={
                'verbose_name': 'veículo',
                'ordering': ['marca', 'modelo'],
            },
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['nome'], 'verbose_name': 'Funcionário'},
        ),
    ]
