# Generated by Django 2.2.7 on 2019-12-01 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20191130_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atendimento', models.DateTimeField(blank=True, null=True, verbose_name='data de partida')),
                ('data_termino', models.DateTimeField(blank=True, null=True, verbose_name='data de chegada')),
                ('destino', models.CharField(max_length=255)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='observação')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Funcionario')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Veiculo')),
            ],
        ),
    ]
