# Generated by Django 2.2.7 on 2019-12-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_atendimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('rg', models.CharField(max_length=14)),
                ('dias_semana', models.CharField(max_length=255)),
                ('faculdade', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'estudante',
                'ordering': ['nome', 'faculdade'],
            },
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='data_termino',
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='data_atendimento',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
