# Generated by Django 2.2.7 on 2019-12-01 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20191201_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudante',
            old_name='dias_semana',
            new_name='curso',
        ),
    ]
